name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: caelifer09/memorygame:${{ github.sha }}
          
      - name: Deploy 
        run: |
            docker stop memorygame || true
            docker rm memorygame || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/memorygame:${{ github.sha }}
            docker run -d --name memorygame -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/memorygame:${{ github.sha }}
